---
- name: Set content specific facts
  ansible.builtin.set_fact:
    file_name: "{{ ansible_date_time.date }}_{{ ansible_network_os.split('.')[2] }}_{{ inventory_hostname }}"
    tmplt_path: "{{ role_path }}/includes/health_checks/templates"
    prepare_path: "{{ role_path }}/includes/prepare"
    delete_path: "{{ role_path }}/includes/delete"
    health_check_path: "{{ role_path }}/includes/health_checks"
    delete_backup_from_dest: false

- name: Check if file copy is possible
  ansible.builtin.include_tasks: "{{ health_check_path }}/{{ network_os }}.yaml"

- name: Copy file from src to a network device
  ansible.netcommon.net_put:
    src: "{{ network_backup_path }}"
    protocol: scp
    dest: "flash:{{ file_name }}.txt"

- name: Prepare appliance for a restore operation
  ansible.builtin.include_tasks: "{{ prepare_path }}/{{ network_os }}.yaml"

- name: Restore operation for {{ network_os }}
  ansible.netcommon.cli_restore:
    force: true
    filename: "{{ file_name }}.txt"

- name: Delete backup from appliance
  ansible.builtin.include_tasks: "{{ delete_path }}/{{ network_os }}.yaml"
  when: delete_backup_from_dest == true
