---
- name: Set content specific facts
  ansible.builtin.set_fact:
    # network_os: "{{ ansible_network_os.split('.')[2] }}"
    cli_restore_path: "{{ role_path }}/includes/cli_restore"

- name: Invoke restore operation
  ansible.builtin.include_tasks: "{{ cli_restore_path }}/{{ network_os }}.yaml"
