---
- name: Set template path
  ansible.builtin.set_fact:
    tmplt_path: "{{ role_path }}/tasks/includes/health_checks/templates"
    prepare_path: "{{ role_path }}/includes/prepare"
    network_os: "{{ ansible_network_os.split('.')[2] }}"

- name: Copy file from src to a network device
  ansible.netcommon.net_put:
    src: "{{ network_backup_path }}"
    protocol: scp
    dest: flash:temp.txt

- name: Prepare appliance for a restore operation
  ansible.builtin.include_tasks: "{{ prepare_path }}/{{ network_os }}.yaml"

- name: Restore operation
  ansible.netcommon.cli_backup:
    force: true
    filename: temp.txt
  register: network_backup
