---
---
- name: Set supported platform list
  ansible.builtin.set_fact:
    supported_cli_restore:
      - "junos"
      - "eos"
    supported_plugin_restore:
      - "nxos"
      - "iosxr"
      - "ios"
    network_os: "{{ ansible_network_os.split('.')[2] }}"

- name: Invoke backup task
  ansible.builtin.include_tasks: includes/cli_restore.yaml
    when: ansible_network_os.split('.')[-1] not in supported_platforms
