---
- name: Set IOSXR directory - content specific facts
  ansible.builtin.set_fact:
    dest_dir: "/misc/scratch/"

- name: Parse free space information
  ansible.utils.cli_parse:
    command: "dir /all | include free"
    parser:
      name: ansible.netcommon.content_templates
      template_path: "{{ tmplt_path }}/{{ network_os }}.yaml"
    set_fact: appliance_dir_data

- name: Check restore file size
  ansible.builtin.stat:
    path: "{{ network_backup_path }}"
  register: restore_file_data

- name: Inspect appliance size
  debug:
    var: appliance_dir_data

- name: Inspect restore file size
  debug:
    var: restore_file_data

- name: Assert file sizes #  needs fix
  assert:
    that: restore_file_data.stat.size < appliance_dir_data.free_bytes
