---
- name: Make file promt quite
  cisco.ios.ios_config:
    lines:
      - "file prompt quiet"

- name: Delete the backup file post backup
  cisco.ios.ios_command:
    commands:
      - command: "delete /force flash:{{ file_name }}.txt"
        # prompt: Delete bootflash:/{{ file_name }}.txt\? \[confirm\]
        # answer: "y"
